# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 16:22
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userstudy', '0002_auto_20171003_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=100)),
                ('related_table_cells', models.CharField(max_length=3000, validators=[django.core.validators.RegexValidator('^(\\([0-9]+,[0-9]+\\)[,\\s]?)*$')])),
                ('annotatorr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('table', models.TextField()),
                ('page_url', models.URLField(max_length=2000)),
                ('page_id', models.PositiveIntegerField()),
                ('table_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention', models.CharField(max_length=200)),
                ('text_mention_start_offset', models.IntegerField()),
                ('text_mention_end_offset', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userstudy.Document')),
            ],
        ),
        migrations.RemoveField(
            model_name='evaluationexample',
            name='answer',
        ),
        migrations.DeleteModel(
            name='EvaluationAnswer',
        ),
        migrations.DeleteModel(
            name='EvaluationExample',
        ),
        migrations.AddField(
            model_name='annotation',
            name='mention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userstudy.Mention'),
        ),
    ]
