# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstudy', '0004_auto_20171004_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='exact',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
