# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userstudy', '0005_annotation_exact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mention_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.TextField()),
                ('table_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='table',
        ),
        migrations.RemoveField(
            model_name='document',
            name='table_id',
        ),
        migrations.AddField(
            model_name='mention',
            name='annotated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='mention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userstudy.Mention_Table'),
        ),
        migrations.AddField(
            model_name='table',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userstudy.Document'),
        ),
        migrations.AddField(
            model_name='mention_table',
            name='mention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userstudy.Mention'),
        ),
        migrations.AddField(
            model_name='mention_table',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userstudy.Table'),
        ),
    ]
