# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstudy', '0006_auto_20171012_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='table',
            new_name='table_html',
        ),
    ]
