# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 10:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userstudy', '0007_auto_20171012_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.PositiveIntegerField()),
                ('page_url', models.URLField(max_length=2000)),
                ('html_content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='page_url',
        ),
        migrations.AlterField(
            model_name='annotation',
            name='related_table_cells',
            field=models.CharField(max_length=3000, validators=[django.core.validators.RegexValidator('^([0-9]+,\\s?)*$')]),
        ),
        migrations.AddField(
            model_name='document',
            name='page',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='userstudy.Page'),
            preserve_default=False,
        ),
    ]
