# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstudy', '0008_auto_20171016_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='skip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mention',
            name='skip',
            field=models.BooleanField(default=False),
        ),
    ]
