# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstudy', '0011_page_assigned_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
