# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstudy', '0012_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
