# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstudy', '0013_page_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='ncells',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='ncols',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='nrows',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
