# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstudy', '0014_auto_20171115_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='exact_match_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='has_table_reference',
            field=models.BooleanField(default=False),
        ),
    ]
