# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstudy', '0015_auto_20171124_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='caption',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='table',
            name='referenced_in_text',
            field=models.BooleanField(default=False),
        ),
    ]
