# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstudy', '0017_page_category_kw_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='comment',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
