# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userstudy', '0019_auto_20171205_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pool',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userstudy.Pool'),
        ),
    ]
