# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userstudy', '0021_mention_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userstudy.Table'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='mention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userstudy.Mention'),
        ),
    ]
