# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstudy', '0022_auto_20171205_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='caption',
            field=models.TextField(default='', null=True),
        ),
    ]
