# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstudy', '0023_auto_20171207_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
