# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstudy', '0024_annotation_ignore'),
    ]

    operations = [
        migrations.AddField(
            model_name='mention_table',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
